name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Azure
        env:
         AZURE_WEBAPP_NAME: curricuai
         AZURE_SP_APP_ID: ${{ secrets.AZURE_SP_APP_ID }}
         AZURE_SP_PASSWORD: ${{ secrets.AZURE_SP_PASSWORD }}
         AZURE_SP_TENANT: ${{ secrets.AZURE_SP_TENANT }}
        run: |
          az login --service-principal --username ${{ secrets.AZURE_SP_APP_ID }} --password ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_SP_TENANT }}
          az webapp up --name $AZURE_WEBAPP_NAME --resource-group imaginecup
